# Label Encoding

In [13]:
# Is converting the labels into a numeric form

In [14]:
# Importing the libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [15]:
# Load the dataset
dataset = pd.read_csv("/Users/balogunishaq/Desktop/Complete Machine Learning Course - Siddhardhan/datasets/breast-cancer-dataset.csv")

In [16]:
dataset

,S/N,Year,Age,Menopause,Tumor Size (cm),Inv-Nodes,Breast,Metastasis,Breast Quadrant,History,Diagnosis Result
0,1,2019,40,1,2,0,Right,0,Upper inner,0,Benign
1,2,2019,39,1,2,0,Left,0,Upper outer,0,Benign
2,3,2019,45,0,4,0,Left,0,Lower outer,0,Benign
3,4,2019,26,1,3,0,Left,0,Lower inner,1,Benign
4,5,2019,21,1,1,0,Right,0,Upper outer,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...
208,209,2020,49,1,6,3,Right,1,Lower inner,1,Malignant
209,210,2020,28,1,3,0,Left,0,Upper inner,0,Benign
210,211,2020,22,1,1,0,Left,0,Upper outer,1,Benign
211,212,2020,19,1,1,0,Left,0,Lower inner,1,Benign
212,213,2020,50,0,4,0,Right,0,Lower outer,1,Benign

In [17]:
dataset.head()

,S/N,Year,Age,Menopause,Tumor Size (cm),Inv-Nodes,Breast,Metastasis,Breast Quadrant,History,Diagnosis Result
0,1,2019,40,1,2,0,Right,0,Upper inner,0,Benign
1,2,2019,39,1,2,0,Left,0,Upper outer,0,Benign
2,3,2019,45,0,4,0,Left,0,Lower outer,0,Benign
3,4,2019,26,1,3,0,Left,0,Lower inner,1,Benign
4,5,2019,21,1,1,0,Right,0,Upper outer,1,Benign

In [18]:
# Finding the count of different labels
dataset['Breast'].value_counts()

Breast
Left     107
Right    100
#          6
Name: count, dtype: int64

In [19]:
# Load the Label Encoder function
label_encode = LabelEncoder()

In [20]:
labels = label_encode.fit_transform(dataset.Breast)

In [21]:
# Append the labels to the DataFrame
dataset['target'] = labels

In [22]:
dataset.head()

,S/N,Year,Age,Menopause,Tumor Size (cm),Inv-Nodes,Breast,Metastasis,Breast Quadrant,History,Diagnosis Result,target
0,1,2019,40,1,2,0,Right,0,Upper inner,0,Benign,2
1,2,2019,39,1,2,0,Left,0,Upper outer,0,Benign,1
2,3,2019,45,0,4,0,Left,0,Lower outer,0,Benign,1
3,4,2019,26,1,3,0,Left,0,Lower inner,1,Benign,1
4,5,2019,21,1,1,0,Right,0,Upper outer,1,Benign,2

In [23]:
# 2 --> Right
# 1 --> Left

In [24]:
dataset['target'].value_counts()

target
1    107
2    100
0      6
Name: count, dtype: int64